ci(gha): report dispatch
Signed-off-by: Peter Mikus <peter.mikus@icloud.com>

diff --git a/.github/workflows/csit-report-dispatch.yml b/.github/workflows/csit-report-dispatch.yml
--- a/.github/workflows/csit-report-dispatch.yml
+++ b/.github/workflows/csit-report-dispatch.yml
@@ -141,8 +141,12 @@ jobs:
                 ;;
           esac
 
-          if [ ${{ inputs.dut }} == "trex" && ${trex:-false} == "false"]; then
+          if [[ ${{ inputs.dut }} == "trex" && ${trex:-false} == "false" ]]; then
               echo "::error::Unsupported Trex/Node combination!"
+              exit 1
+          fi
+          if [[ ${{ inputs.dut }} == "dpdk" && ${dpdk:-false} == "false" ]]; then
+              echo "::error::Unsupported DPDK/Node combination!"
               exit 1
           fi
           echo "matrix={\"include\":[{\"node\":\"${{ inputs.node }}\",\"executor_arch\":\"$executor_arch\",\"os\":\"$os\",\"dut\":\"${{ inputs.dut }}\",}]}" >> $GITHUB_OUTPUT
