ci(gha): report dispatch
Signed-off-by: Peter Mikus <peter.mikus@icloud.com>

diff --git a/.github/workflows/csit-report-dispatch.yml b/.github/workflows/csit-report-dispatch.yml
--- a/.github/workflows/csit-report-dispatch.yml
+++ b/.github/workflows/csit-report-dispatch.yml
@@ -61,101 +61,90 @@ jobs:
         run: |
           case "${{ inputs.node }}" in
             "2n-emr")
-                if [ ${{ inputs.dut }} == "trex" ]; then
-                    echo "::notice::Unsupported combination!"
-                    exit 1
-                fi
+                dpdk="true"
                 executor_arch="x86_64"
                 os="ubuntu2404"
                 ;;
             "2n-grc")
-                if [ ${{ inputs.dut }} == "trex" ]; then
-                    echo "::notice::Unsupported combination!"
-                    exit 1
-                fi
-                executor_arch="x86_64"
+                dpdk="true"
+                executor_arch="aarch64"
                 os="ubuntu2404"
                 ;;
             "2n-icx")
+                dpdk="true"
+                trex="true"
                 executor_arch="x86_64"
                 os="ubuntu2404"
                 ;;
             "2n-spr")
+                dpdk="true"
+                trex="true"
                 executor_arch="x86_64"
                 os="ubuntu2404"
                 ;;
             "2n-zn2")
-                if [ ${{ inputs.dut }} == "trex" ]; then
-                    echo "::notice::Unsupported combination!"
-                    exit 1
-                fi
+                dpdk="true"
                 executor_arch="x86_64"
                 os="ubuntu2404"
                 ;;
             "3n-alt")
-                if [ ${{ inputs.dut }} == "trex" ]; then
-                    echo "::notice::Unsupported combination!"
-                    exit 1
-                fi
-                executor_arch="x86_64"
+                dpdk="true"
+                executor_arch="aarch64"
                 os="ubuntu2404"
                 ;;
             "3n-emr")
-                if [ ${{ inputs.dut }} == "trex" ]; then
-                    exit 1
-                fi
+                dpdk="true"
                 executor_arch="x86_64"
                 os="ubuntu2404"
                 ;;
             "3n-icx")
-                if [ ${{ inputs.dut }} == "trex" ]; then
-                    echo "::notice::Unsupported combination!"
-                    exit 1
-                fi
+                dpdk="true"
                 executor_arch="x86_64"
                 os="ubuntu2404"
                 ;;
             "3n-icxd")
-                if [ ${{ inputs.dut }} == "trex" ]; then
-                    echo "::notice::Unsupported combination!"
-                    exit 1
-                fi
+                dpdk="true"
                 executor_arch="x86_64"
                 os="ubuntu2404"
                 ;;
             "3n-oct")
-                if [ ${{ inputs.dut }} == "trex" ]; then
-                    echo "::notice::Unsupported combination!"
-                    exit 1
-                fi
-                executor_arch="x86_64"
+                dpdk="true"
+                executor_arch="aarch64"
                 os="ubuntu2404"
                 ;;
             "3n-snr")
-                if [ ${{ inputs.dut }} == "trex" ]; then
-                    echo "::notice::Unsupported combination!"
-                    exit 1
-                fi
+                dpdk="true"
                 executor_arch="x86_64"
                 os="ubuntu2404"
                 ;;
             "3na-spr")
-                if [ ${{ inputs.dut }} == "trex" ]; then
-                    echo "::notice::Unsupported combination!"
-                    exit 1
-                fi
+                dpdk="true"
                 executor_arch="x86_64"
                 os="ubuntu2404"
                 ;;
             "3nb-spr")
-                if [ ${{ inputs.dut }} == "trex" ]; then
-                    echo "::notice::Unsupported combination!"
-                    exit 1
-                fi
+                dpdk="true"
                 executor_arch="x86_64"
                 os="ubuntu2404"
                 ;;
+            "2n-aws")
+                executor_arch="x86_64"
+                os="ubuntu2404"
+                ;;
+            "2n-c6in")
+                executor_arch="x86_64"
+                os="ubuntu2404"
+                ;;
+            "2n-c7gn")
+                executor_arch="aarch64"
+                os="ubuntu2404"
+                ;;
           esac
+
+          if [ ${{ inputs.dut }} == "trex" && -z ${trex+x} ]; then
+              echo "::error::Unsupported Trex/Node combination!"
+              exit 1
+          fi
           echo "matrix={\"include\":[{\"node\":\"${{ inputs.node }}\",\"executor_arch\":\"$executor_arch\",\"os\":\"$os\",\"dut\":\"${{ inputs.dut }}\",}]}" >> $GITHUB_OUTPUT
 
   csit-perf-report:
